version: '3.8'

services:

  snapshot-mysql:
    platform: linux/amd64
    container_name: snapshot-mysql
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "pwd"
      MYSQL_ROOT_PASSWORD: "pwd"
      MYSQL_DATABASE: "snapshot"
    volumes:
        - "./snapshot-hub/database/:/docker-entrypoint-initdb.d/"
    networks:
      - default
      - shared-network

  redis:
    platform: linux/arm64
    container_name: redis
    image: redis
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - 6379:6379
    volumes:
      - ./redis/api/.db:/data
    restart: always
    entrypoint: redis-server --appendonly yes
    networks:
      - default

  snapshot-hub:
    platform: linux/arm64
    container_name: snapshot-hub
    build:
      context: ../modules/snapshot-hub
      dockerfile: ../../docker/snapshot-hub/Dockerfile
    env_file:
      - ./snapshot-hub/.env
    depends_on:
      - snapshot-mysql 
      - score-api
    ports:
      - "3000:3000"
    networks:
      - default
      - keycard-network
      - shared-network

  snapshot-seq:
    platform: linux/arm64
    container_name: snapshot-seq
    build:
      context: ../modules/snapshot-sequencer
      dockerfile: ../../docker/snapshot-sequencer/Dockerfile
    env_file:
      - ./snapshot-sequencer/.env
    depends_on:
      - snapshot-mysql
      - score-api
      - redis
    ports:
      - "3001:3001"
    networks:
      - default
      - keycard-network
      - shared-network

  score-api:
    platform: linux/arm64
    container_name: score-api
    build:
      context: ../modules/score-api
      dockerfile: ../../docker/score-api/Dockerfile
    depends_on:
      - redis
    ports:
      - "3003:3003"
    env_file:
      - ./score-api/.env
    networks:
      - default
      - keycard-network

  keycard-mysql:
    container_name: keycard-mysql
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "pwd"
      MYSQL_ROOT_PASSWORD: "pwd"
      MYSQL_DATABASE: "keycard"
    networks:
      - keycard-network
    volumes:
      - "./keycard/schema.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./keycard/seed.sql:/docker-entrypoint-initdb.d/2.sql"
      - "./keycard/database/:/docker-entrypoint-initdb-keycard.d/"

  keycard:
    container_name: keycard
    build:
      context: ../modules/keycard
      dockerfile: ../../docker/keycard/Dockerfile
    ports:
      - "3007:3007"
    depends_on:
      - keycard-mysql
    env_file:
      - ./keycard/.env
    networks:
      - default
      - keycard-network

  snapshot-interface:
    container_name: snapshot-interface
    build:
      context: ../modules/snapshot
      dockerfile: ../../docker/snapshot/Dockerfile
    ports:
      - "8080:8080" 
    env_file:
      - ./snapshot/.env
    networks:
      - default
      - shared-network  
    
networks:
  keycard-network:
    name: keycard-network 
  default:
    name: snapshot-network
  shared-network:
    external: true  